# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "openstack-destroy"
  config.vm.box_url = "https://s3-sa-east-1.amazonaws.com/willian-boxes/UbuntuServer12.04amd64.box"
  # config.vm.boot_mode = :gui
  config.vm.network :bridged
  config.vm.network :hostonly, "192.168.100.15"
  config.vm.forward_port 80, 8888
  config.vm.forward_port 6080, 6080
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "openstack-destroy.pp"
  end
end
